apiVersion: v1
kind: Service
metadata:
  name: lanchonete-self-service
spec:
  selector:
    app: lanchonete-self-service-deployment
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer