apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
type: Opaque
data:
  MYSQL_DATABASE: bXlkYg==
  MYSQL_USER: dGVjaGNoYWxsZW5nZQ==
  MYSQL_PASSWORD: dGVjaGNoYWxsZW5nZQ==
  MYSQL_ROOT_PASSWORD: dGVjaGNoYWxsZW5nZQ==